from fastapi import APIRouter, Depends, HTTPException, Query

from app.core.auth import verify_token
from app.db import history as db
from app.schemas.history import (
    FullHistory,
    PaginatedCaregiverSummaries,
    PaginatedIntents,
    PaginatedSessions,
    SessionDetail,
)

router = APIRouter(prefix="/api/history", tags=["history"])


@router.get("/all", response_model=FullHistory)
def get_all_history(user=Depends(verify_token)):
    """
    Return all chat sessions (with messages) and caregiver summaries for the
    authenticated user in a single response.
    """
    return db.get_all_history(user.id)


@router.get("/sessions", response_model=PaginatedSessions)
def list_sessions(
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    user=Depends(verify_token),
):
    """List AI chat sessions for the authenticated user, newest first."""
    data, total = db.get_sessions(user.id, page=page, page_size=page_size)
    return PaginatedSessions(data=data, total=total, page=page, page_size=page_size)


@router.get("/sessions/{session_id}", response_model=SessionDetail)
def get_session(session_id: str, user=Depends(verify_token)):
    """Get a single session with all its messages in order."""
    result = db.get_session_with_messages(session_id, user.id)
    if not result:
        raise HTTPException(status_code=404, detail="Session not found")
    return result


@router.get("/intents", response_model=PaginatedIntents)
def list_intents(
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    user=Depends(verify_token),
):
    """List intent parsing history for the authenticated user, newest first."""
    data, total = db.get_intent_history(user.id, page=page, page_size=page_size)
    return PaginatedIntents(data=data, total=total, page=page, page_size=page_size)


@router.get("/caregiver-summaries", response_model=PaginatedCaregiverSummaries)
def list_caregiver_summaries(
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    user=Depends(verify_token),
):
    """List AI health analysis reports generated by the authenticated caregiver."""
    data, total = db.get_caregiver_summaries(user.id, page=page, page_size=page_size)
    return PaginatedCaregiverSummaries(data=data, total=total, page=page, page_size=page_size)
